trigger:
- Dev

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      python.version: '3.9'
 
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    cd cosmosdb-with-fastapi
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: UsePythonVersion@0
- script: |
    pip install pytest && pip install build
    python -m build
    python -m pytest
    pwd
    ls -la
  displayName: 'Build and test '
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact: my-package'
  inputs:
    artifactName: 'my-package'
    pathToPublish: 'dist/*'
